# Generated by Django 3.0.5 on 2020-04-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('date_livraison_ini', models.DateField(verbose_name='Date de livraison initiale')),
                ('date_livraison_act', models.DateField(verbose_name='Date de livraison prévue')),
                ('statut_livraison', models.CharField(choices=[(1, 'En commercialisation'), (2, 'En construction'), (3, 'Terminé')], max_length=1)),
                ('promoteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Promoteur')),
            ],
        ),
    ]
