# Generated by Django 3.0.5 on 2021-09-28 14:22

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('date_livraison_ini', models.DateField(verbose_name='Date de livraison initiale')),
                ('date_livraison_act', models.DateField(blank=True, null=True, verbose_name='Date de livraison prévue')),
                ('statut', models.IntegerField(choices=[(1, 'En commercialisation'), (2, 'En construction'), (3, 'Terminé')])),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=255, populate_from='nom')),
            ],
        ),
        migrations.CreateModel(
            name='Promoteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=1500, null=True)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Programme')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='promoteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Promoteur'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(blank=True, max_length=1500, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=255, populate_from='title')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Subject')),
            ],
        ),
    ]
