# Generated by Django 3.0.5 on 2021-09-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
    ]
