# Generated by Django 3.0.5 on 2021-09-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0002_remove_post_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='monimmo.Subject'),
            preserve_default=False,
        ),
    ]
