# Generated by Django 3.0.5 on 2021-09-28 15:41

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0004_auto_20210928_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=True, max_length=255, populate_from='title'),
        ),
    ]
