# Generated by Django 3.0.5 on 2020-06-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0004_auto_20200601_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='statut_livraison',
            field=models.CharField(choices=[(1, 'En commercialisation'), (2, 'En construction'), (3, 'Terminé')], max_length=40),
        ),
    ]
