# Generated by Django 3.0.5 on 2020-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0005_auto_20200602_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
