# Generated by Django 3.0.5 on 2022-01-01 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monimmo', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='programme',
            name='owner',
            field=models.ManyToManyField(through='monimmo.Reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
