# Generated by Django 3.0.5 on 2020-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0007_auto_20200603_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='statut',
            field=models.IntegerField(choices=[(1, 'En commercialisation'), (2, 'En construction'), (3, 'Terminé')]),
        ),
    ]
