# Generated by Django 3.0.5 on 2022-01-03 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0008_auto_20220101_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monimmo.Programme')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monimmo.Building'),
            preserve_default=False,
        ),
    ]
