# Generated by Django 3.0.5 on 2020-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0009_auto_20200603_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
