# Generated by Django 3.0.5 on 2020-06-25 10:27

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0010_auto_20200603_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=255, populate_from=('nom',)),
        ),
    ]
