# Generated by Django 3.0.5 on 2020-06-25 15:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0011_programme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, max_length=255, populate_from='nom'),
        ),
    ]
