# Generated by Django 3.0.5 on 2022-03-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0011_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='building',
        ),
    ]
