# Generated by Django 3.0.5 on 2020-06-25 16:01

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0012_auto_20200625_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='dddC', editable=False, max_length=255, populate_from='nom'),
        ),
    ]
