# Generated by Django 3.0.5 on 2022-03-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0012_remove_reservation_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='app_ref',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
