# Generated by Django 3.0.5 on 2020-06-25 16:05

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0013_auto_20200625_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=True, max_length=255, populate_from='nom'),
        ),
    ]
