# Generated by Django 3.0.5 on 2022-04-21 15:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0013_auto_20220307_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
