# Generated by Django 3.0.5 on 2022-04-21 16:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0015_auto_20220421_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
