# Generated by Django 3.0.5 on 2022-04-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0017_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
