# Generated by Django 3.0.5 on 2022-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0019_auto_20220425_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
