# Generated by Django 3.0.5 on 2022-05-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monimmo', '0020_profile_avatar_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
    ]
